# .github/workflows/update_commits.yml
name: Update Commits

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Requests
        run: pip install requests

      - name: Run script
        run: python app/fetch_commits.py
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add commit.json
          git commit -m "Update commit.json"
          git push
